#!/usr/bin/env python3
# -*- coding: utf8 -*-
# Simple alternative to running `setup.py install` or `setup.py develop`
import ngsreports.main


if __name__ == "__main__":
    ngsreports.main.entry_point()
