#!/bin/bash

set -o nounset # Fail on unset variables
set -o errexit # Fail on uncaught non-zero returncodes
set -o pipefail # Fail is a command in a chain of pipes fails

if [ $# -ne 2 ];
then
    echo "Usage:" > /dev/stderr
    echo "\$ $0 /path/to/config/ /path/to/data/" > /dev/stderr
    exit 1
elif [ ! -e "$1/config.ini" ];
then
    echo "'$1/config.ini' not found" > /dev/stderr

    exit 1
fi

# The login-token lasts 3 hours, so it is necessary to login before every task
az acr login --name cfbregistry --resource-group rg-cfb-common

# The `-u` option ensures that files created in /config are owned by the current user
docker run --rm --interactive -u "$(id -u):$(id -g)" \
    -v "$1:/config" \
    -v "$2:/data:shared" \
    cfbregistry.azurecr.io/monitor-proteomics:TAG \
        --config /config/config.ini
